packages:
  - workflow
  - model
  - ui
  - block

catalog:
  '@platforma-sdk/workflow-tengo': ^2.13.0
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.59
  '@platforma-sdk/tengo-builder': ^1.17.7
  '@platforma-sdk/block-tools': ^2.5.14

  '@milaboratories/graph-maker': ^1.1.47
  '@milaboratories/software-pframes-conv': ^2.1.12
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.11
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-139-develop

  '@platforma-sdk/test': ^1.22.59

  'vue': ^3.5.13
  'vue-tsc': ^2.2.4

  'typescript': ~5.7.3
  'tsup': ~8.3.6
  'turbo': ^2.4.2

  'vite': ^6.1.1
  'vitest': ^3.0.6
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
