packages:
  - workflow
  - model
  - ui
  - block

catalog:
  '@platforma-sdk/workflow-tengo': ^2.8.4
  '@platforma-sdk/model': ^1.20.11
  '@platforma-sdk/ui-vue': ^1.20.19
  '@platforma-sdk/tengo-builder': ^1.17.4
  '@platforma-sdk/block-tools': ^2.5.0

  '@milaboratories/graph-maker': ^1.1.15
  '@milaboratories/software-pframes-conv': ^2.1.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.0
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-137-develop

  '@platforma-sdk/test': ^1.20.12

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  'typescript': ~5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^6.0.3
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.27.10
